# web port
server:
  port: 8082
spring:
  redis:
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://rm-bp14r1ey9m7f6tg92fo.mysql.rds.aliyuncs.com:3306/test?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: lsc
    password: Lscqet159753
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sftp:
  host: 39.105.183.1
  port: 30222
  userName: gmrb
  pwd: gmrb12#
rocketmq:
  enable: false
  name-server: localhost:9876
  producer:
    group: my-group
    send-message-timeout: 777777
spring.servlet.multipart:
  enabled: true                 # 设置支持的单个上传文件的大小限制
  max-file-size: 10MB           # 设置最大的请求文件大小，设置总体大小请求
  max-request-size: 20MB



