# web port
server:
  port: 8082
spring:
  redis:
    host: 127.0.0.1
#spring:
#  datasource:
#    url: jdbc:mysql://8.140.153.247:3306/newsdb
#    username: root
#    password: 0P-0p-0p-
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    show-sql: true

sftp:
  host: 39.105.183.1
  port: 30222
  userName: gmrb
  pwd: gmrb12#
rocketmq:
  enable: false
  name-server: 127.0.0.1:9876
  producer:
    group: my-group
    send-message-timeout: 777777
spring.servlet.multipart:
  enabled: true                 # 设置支持的单个上传文件的大小限制
  max-file-size: 10MB           # 设置最大的请求文件大小，设置总体大小请求
  max-request-size: 20MB



